const C={blue:'#118DFF',navy:'#12239E',orange:'#E66C37',purple:'#6B007B',pink:'#E044A7',green:'#1AAB40',gold:'#D9B300'};
const ownerColors=count=>Array.from({length:count},(_,index)=>`hsl(${Math.round(index*360/count)} 68% 48%)`);
let orders=[],page='resumen', filtered=[]; const $=s=>document.querySelector(s); const sum=(a,key)=>a.reduce((n,x)=>n+(typeof key==='function'?key(x):x[key]),0); const group=(a,key)=>Object.entries(a.reduce((o,x)=>((o[key(x)]=(o[key(x)]||0)+1),o),{}));
const dayGroups=()=>group(filtered,x=>x.date.slice(8)).sort((a,b)=>Number(a[0])-Number(b[0]));
const yearOrders=()=>{const year=$('#yearFilter').value;return orders.filter(x=>year==='Todos'||x.date.startsWith(year))};
const monthName=key=>new Date(`${key}-01T00:00:00`).toLocaleDateString('es-ES',{month:'long'});
const monthGroups=rows=>group(rows,x=>x.date.slice(0,7)).sort((a,b)=>a[0].localeCompare(b[0]));
const priorityOrder=['Alta','Media','Baja'];
const priorityLabel=value=>{const normalized=String(value||'Sin prioridad').trim().toLowerCase();if(normalized==='critica'||normalized==='crítica'||normalized==='urgente')return 'Crítica/Urgente';return normalized.replace(/^./,letter=>letter.toUpperCase())};
const priorityGroups=rows=>{const totals=new Map(priorityOrder.map(priority=>[priority,0]));let criticalUrgent=0;rows.forEach(row=>{const priority=priorityLabel(row.priority);if(priority==='Crítica/Urgente')criticalUrgent++;else totals.set(priority,(totals.get(priority)||0)+1)});totals.set('Crítica/Urgente',criticalUrgent);return [...totals.entries()]};
function normalizeOrder(order){
 const date=String(order.fecha_inicio||'').slice(0,10);
 return {id:order.id,date,sector:order.sector||'Sin sector',status:order.progreso||'Sin estado',priority:order.prioridad||'Sin prioridad',support:order.apoyo||'Sin apoyo',owner:order.responsable||'Sin responsable',machine:order.maquina_equipo||'Sin equipo',hours:Number(order.horas)||0,downtime:Number(order.horas_paro)||0,monthHours:Number(order.horas_mes)||0,cost:Number(order.total_costo)||0};
}
async function loadOrders(){
 if(!localStorage.getItem('token')){if(new URLSearchParams(window.location.search).has('embed')){$('#dashboard').innerHTML='<div class="empty session-required">Debe iniciar sesión para visualizar el reporte.</div>';return false}window.location.href='../index.html';return false}
 try{
  const response=await API_FETCH('/api/ordenes');
  if(!response.ok) throw new Error(`No se pudieron cargar las órdenes (${response.status})`);
  orders=(await response.json()).map(normalizeOrder);
  filtered=[...orders];
  return true;
 }catch(error){
  console.error('Error cargando órdenes del reporte:',error);
  $('#dashboard').innerHTML='<div class="empty">No se pudieron cargar las órdenes. Verifique su sesión e inténtelo nuevamente.</div>';
  return false;
 }
}
function svg(w=600,h=210){return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Gráfico"><line class="axis" x1="45" y1="180" x2="${w-10}" y2="180"/><line class="axis" x1="45" y1="12" x2="45" y2="180"/>`;}
function barChart(data, horizontal=false, colors=[C.blue]){let max=Math.max(...data.map(x=>x[1]))||1,w=600,h=210,plot=horizontal?145:168;let marks=data.map(([n,v],i)=>{let c=colors[i%colors.length];if(horizontal){let y=18+i*(plot/data.length),bw=(v/max)*490;return `<text class="axis-label" x="4" y="${y+11}">${n}</text><rect x="102" y="${y}" width="${bw}" height="18" fill="${c}"><title>${n}: ${v}</title></rect><text class="axis-label" x="${106+bw}" y="${y+13}">${v}</text>`}let x=55+i*(520/data.length),bw=420/data.length,ht=(v/max)*145;return `<rect x="${x}" y="${180-ht}" width="${bw}" height="${ht}" fill="${c}"><title>${n}: ${v}</title></rect><text class="axis-label" text-anchor="middle" x="${x+bw/2}" y="198">${n}</text><text class="axis-label" text-anchor="middle" x="${x+bw/2}" y="${174-ht}">${v}</text>`}).join('');return svg(w,h)+marks+'</svg>'}
function ownerProgressChart(rows){const owners=[...new Set(rows.map(x=>x.owner))],statuses=[...new Set(rows.map(x=>x.status))],colors=[C.blue,C.orange,C.green,C.purple,C.gold],counts=rows.reduce((result,row)=>{const key=`${row.owner}|${row.status}`;result[key]=(result[key]||0)+1;return result},{}),max=Math.max(...owners.map(owner=>statuses.reduce((total,status)=>total+(counts[`${owner}|${status}`]||0),0)))||1,height=Math.max(210,owners.length*34+35),marks=owners.map((owner,index)=>{const y=25+index*34;let offset=0;const segments=statuses.map((status,statusIndex)=>{const value=counts[`${owner}|${status}`]||0,width=value/max*430,x=125+offset;offset+=width;return value?`<rect x="${x}" y="${y}" width="${width}" height="20" fill="${colors[statusIndex%colors.length]}"><title>Responsable: ${owner} | Progreso: ${status} | ${value} órdenes</title></rect>`:''}).join('');return `<text class="axis-label" x="4" y="${y+14}">${owner}</text>${segments}`}).join('');const legend=statuses.map((status,index)=>`<text class="axis-label" x="${125+index*105}" y="${height-5}"><tspan fill="${colors[index%colors.length]}">●</tspan> ${status}</text>`).join('');return `<svg viewBox="0 0 600 ${height}" role="img" aria-label="Órdenes por responsable y progreso"><line class="axis" x1="125" y1="12" x2="125" y2="${height-25}"/>${marks}${legend}</svg>`}
function sectorProgressChart(rows){const sectors=[...new Set(rows.map(x=>x.sector))],statuses=['Completado','No iniciado','Asignado','Reprogramado'],colors=[C.green,C.orange,C.blue,C.purple],statusLabel=status=>status==='Asignada'?'Asignado':status,counts=rows.reduce((result,row)=>{const status=statuses.includes(statusLabel(row.status))?statusLabel(row.status):'Otros';const key=`${row.sector}|${status}`;result[key]=(result[key]||0)+1;return result},{}),max=Math.max(...sectors.map(sector=>Object.keys(counts).filter(key=>key.startsWith(`${sector}|`)).reduce((total,key)=>total+counts[key],0)))||1,height=Math.max(210,sectors.length*34+42),marks=sectors.map((sector,index)=>{const y=22+index*34;let offset=0;const segments=[...statuses,'Otros'].map((status,statusIndex)=>{const value=counts[`${sector}|${status}`]||0,width=value/max*430,x=125+offset;offset+=width;const color=status==='Otros'?'#9aa8b5':colors[statusIndex];return value?`<rect x="${x}" y="${y}" width="${width}" height="20" fill="${color}"><title>Sector: ${sector} | Progreso: ${status} | ${value} órdenes</title></rect>`:''}).join('');return `<text class="axis-label" x="4" y="${y+14}">${sector}</text>${segments}`}).join(''),legend=[...statuses,'Otros'].map((status,index)=>`<text class="axis-label" x="${125+index*105}" y="${height-5}"><tspan fill="${status==='Otros'?'#9aa8b5':colors[index]}">●</tspan> ${status}</text>`).join('');return `<svg viewBox="0 0 600 ${height}" role="img" aria-label="Órdenes por sector y progreso"><line class="axis" x1="125" y1="12" x2="125" y2="${height-25}"/>${marks}${legend}</svg>`}
function lineChart(data,unit='órdenes',shaded=false){let max=Math.max(...data.map(x=>x[1]))||1,points=data.map(([n,v],i)=>({name:n,value:v,x:55+i*(510/(data.length-1||1)),y:180-(v/max)*145})),pts=points.map(point=>`${point.x},${point.y}`).join(' '),area=shaded&&points.length?`<polygon points="${points[0].x},180 ${pts} ${points[points.length-1].x},180" fill="${C.blue}" opacity=".16"/>`:'';return svg()+area+`<polyline points="${pts}" fill="none" stroke="${C.blue}" stroke-width="3"/>`+points.map(point=>`<circle cx="${point.x}" cy="${point.y}" r="4" fill="${C.blue}"><title>${point.name}: ${point.value} ${unit}</title></circle><text class="axis-label" text-anchor="middle" x="${point.x}" y="198">${point.name}</text>`).join('')+'</svg>'}
function donut(data,colors=[C.blue,C.orange,C.green,C.purple,C.gold],label=''){let total=sum(data,x=>x[1]),offset=0,parts=data.map(([n,v],i)=>{let pct=v/total, dash=`${pct*251.2} ${251.2-pct*251.2}`,color=colors[i%colors.length],s=`<circle cx="105" cy="105" r="40" fill="none" stroke="${color}" stroke-width="28" stroke-dasharray="${dash}" stroke-dashoffset="${-offset}" transform="rotate(-90 105 105)"><title>${label?`${label}: `:''}${n}: ${v} órdenes</title></circle>`;offset+=pct*251.2;return s}).join('');return `<div class="donut-layout"><svg viewBox="0 0 210 210"><circle cx="105" cy="105" r="40" fill="none" stroke="#e7e5e3" stroke-width="28"/>${parts}<text x="105" y="101" text-anchor="middle" font-size="25" fill="#252423">${total}</text><text x="105" y="119" text-anchor="middle" font-size="11" fill="#605e5c">órdenes</text></svg><div class="legend">${data.map(([n,v],i)=>`<div><i style="background:${colors[i%colors.length]}"></i>${n}: ${v}</div>`).join('')}</div></div>`}
function priorityBreakdown(rows){const statusColors=[C.green,C.orange,C.blue,C.purple,C.gold];return priorityGroups(rows).map(([priority])=>{const priorityRows=rows.filter(row=>priorityLabel(row.priority)===priority),progress=group(priorityRows,x=>x.status);return `<article class="visual priority-breakdown-card"><h3>${priority}: distribución de progreso</h3><div class="visual-content">${donut(progress,statusColors,`Prioridad ${priority}`)}</div></article>`}).join('')}
function table(rows,cols){return `<table class="data-table"><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(([k])=>`<td>${k==='status'?`<span class="status ${r[k].replace(' ','-')}">${r[k]}</span>`:r[k]}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function visual(id,html){const target=document.querySelector(`#${id} .visual-content`);if(target)target.innerHTML=html}
function kpis(){let done=filtered.filter(x=>x.status==='Completado').length,cost=sum(filtered,'cost');$('#resumen-kpis').innerHTML=`<div class="kpi"><span>Órdenes de mantenimiento</span><strong>${filtered.length}</strong><em>Período seleccionado</em></div><div class="kpi"><span>Órdenes completadas</span><strong>${done}</strong><em>${filtered.length?Math.round(done/filtered.length*100):0}% del total</em></div><div class="kpi"><span>Costo total</span><strong>Gs. ${cost.toLocaleString('es-PY')}</strong><em>Repuestos y mano de obra</em></div>`}
function render(){document.querySelectorAll('[data-page-section]').forEach(section=>{section.hidden=section.dataset.pageSection!==page;section.querySelectorAll('.visual-content').forEach(content=>{content.innerHTML=''});section.querySelector('.report-empty')?.remove()});if(!filtered.length&&page!=='operacion'){const section=document.querySelector(`[data-page-section="${page}"]`);section.querySelector('.dashboard').insertAdjacentHTML('beforeend','<div class="empty report-empty">No hay órdenes para la combinación de filtros seleccionada.</div>');return}let by=(key)=>group(filtered,x=>x[key]);if(page==='resumen'){kpis();visual('resumen-ordenes-dia',lineChart(dayGroups().map(([n,v])=>[n,v])));visual('resumen-progreso',donut(by('status')));const owners=by('owner');visual('resumen-responsable',donut(owners,ownerColors(owners.length),'Responsable'));visual('resumen-costo-dia',lineChart(dayGroups().map(([n])=>[n,sum(filtered.filter(x=>x.date.endsWith(n)),'cost')]),'Gs.'));visual('resumen-prioridad',barChart(by('priority'),true,[C.orange,C.purple,C.gold,C.blue]));visual('resumen-apoyo',donut(by('support')))}
else if(page==='operacion'){const annual=yearOrders(),months=monthGroups(annual),monthlyOrders=months.map(([key,total])=>[monthName(key),total]),monthlyCosts=months.map(([key])=>[monthName(key),sum(annual.filter(x=>x.date.startsWith(key)),'cost')]),costRows=[...months.map(([key])=>({month:monthName(key),cost:`Gs. ${sum(annual.filter(x=>x.date.startsWith(key)),'cost').toLocaleString('es-PY')}`})),{month:'Total',cost:`Gs. ${sum(annual,'cost').toLocaleString('es-PY')}`}];visual('operacion-responsable',ownerProgressChart(filtered));visual('operacion-prioridad',barChart(by('priority'),false,[C.orange,C.purple,C.gold,C.blue]));visual('operacion-resumen-progreso',donut(by('status')));visual('operacion-ordenes-mes',barChart(monthlyOrders));visual('operacion-costo',table(costRows,[['month','Mes'],['cost','Costo']]));visual('operacion-costo-mes',lineChart(monthlyCosts,'Gs.',true))}
else if(page==='detalle'){visual('detalle-ordenes',table(filtered,[['id','ID'],['machine','Máquina/equipo'],['status','Progreso'],['owner','Responsable'],['hours','Horas'],['cost','Total costo']]))}
else if(page==='indicadores'){const machines=Object.values(filtered.reduce((result,order)=>{const machine=result[order.machine]??={machine:order.machine,count:0,downtime:0,months:{}};machine.count++;machine.downtime+=order.downtime;machine.months[order.date.slice(0,7)]=Math.max(machine.months[order.date.slice(0,7)]||0,order.monthHours);result[order.machine]=machine;return result},{})).map(machine=>{const monthHours=sum(Object.values(machine.months),value=>value),operatingHours=Math.max(monthHours-machine.downtime,0),mtbr=machine.count?operatingHours/machine.count:0,mttf=machine.count?monthHours/machine.count:0,availability=monthHours?(operatingHours/monthHours)*100:0;return{machine:machine.machine,count:machine.count,downtime:machine.downtime,monthHours,mtbr,mttf,availability}});visual('indicadores-equipos',table(machines.map(machine=>({...machine,downtime:`${machine.downtime.toFixed(1)} h`,monthHours:`${machine.monthHours.toFixed(1)} h`,mtbr:`${machine.mtbr.toFixed(1)} h`,mttf:`${machine.mttf.toFixed(1)} h`,availability:`${machine.availability.toFixed(1)}%`})),[['machine','Máquina/equipo'],['count','Recuento de ID'],['downtime','Horas de paro'],['monthHours','Horas mes'],['mtbr','MTBR'],['mttf','MTTF'],['availability','Disponibilidad']]))}
else if(page==='sector'){const sectorRows=Object.values(filtered.reduce((result,order)=>{const row=result[order.sector]??={sector:order.sector,total:0,completed:0,notStarted:0,assigned:0,rescheduled:0,other:0};row.total++;const status=order.status==='Asignada'?'Asignado':order.status;if(status==='Completado')row.completed++;else if(status==='No iniciado')row.notStarted++;else if(status==='Asignado')row.assigned++;else if(status==='Reprogramado')row.rescheduled++;else row.other++;result[order.sector]=row;return result},{})),sectorTotal=sectorRows.reduce((total,row)=>{Object.keys(total).forEach(key=>{if(key!=='sector')total[key]+=row[key]});return total},{sector:'Total',total:0,completed:0,notStarted:0,assigned:0,rescheduled:0,other:0});visual('sector-progreso',sectorProgressChart(filtered));visual('sector-detalle',table([...sectorRows,sectorTotal],[['sector','Sector'],['total','Total'],['completed','Completado'],['notStarted','No iniciado'],['assigned','Asignado'],['rescheduled','Reprogramado'],['other','Otros']]))}
else {visual('prioridad-global',barChart(priorityGroups(filtered),false,[C.orange,C.purple,C.gold,C.blue,C.purple]));$('#prioridad-desglose').innerHTML=priorityBreakdown(filtered)} }
function initFilters(){const dates=orders.map(x=>x.date).filter(Boolean),today=new Date(),currentYear=String(today.getFullYear()),currentMonth=today.toLocaleDateString('es-ES',{month:'long'}),years=[...new Set(dates.map(x=>x.slice(0,4)))].sort((a,b)=>Number(a)-Number(b)),monthValues=[...new Set(dates.map(x=>{const date=new Date(`${x}T00:00:00`);return{label:date.toLocaleDateString('es-ES',{month:'long'}),index:date.getMonth()}}))].sort((a,b)=>a.index-b.index).map(x=>x.label),opts=(id,vals,defaultValue='Todos')=>{const select=$(id);select.innerHTML='';[...new Set(vals)].forEach(value=>select.insertAdjacentHTML('beforeend',`<option value="${value}">${value}</option>`));select.insertAdjacentHTML('beforeend','<option value="Todos">Todos</option>');select.value=vals.includes(defaultValue)?defaultValue:'Todos'};const setDefaultFilters=()=>{$('#yearFilter').value=years.includes(currentYear)?currentYear:'Todos';$('#monthFilter').value=monthValues.includes(currentMonth)?currentMonth:'Todos';$('#statusFilter').value='Todos';$('#priorityFilter').value='Todos'};opts('#yearFilter',years);opts('#monthFilter',monthValues);opts('#statusFilter',[...new Set(orders.map(x=>x.status))]);opts('#priorityFilter',[...new Set(orders.map(x=>x.priority))]);setDefaultFilters();document.querySelectorAll('select').forEach(s=>s.addEventListener('change',apply));$('.tabs').addEventListener('click',e=>{if(!e.target.matches('.tab'))return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');page=e.target.dataset.page;render()});$('#resetFilters').addEventListener('click',()=>{setDefaultFilters();apply()});$('#toggleFilters').addEventListener('click',()=>{const app=document.querySelector('.app'),button=$('#toggleFilters'),collapsed=app.classList.toggle('filters-collapsed');button.setAttribute('aria-expanded',String(!collapsed));button.textContent=collapsed?'☰ Mostrar filtros':'☰ Ocultar filtros'})}
function apply(){let y=$('#yearFilter').value,m=$('#monthFilter').value,s=$('#statusFilter').value,p=$('#priorityFilter').value;filtered=orders.filter(x=>{const month=x.date?new Date(`${x.date}T00:00:00`).toLocaleDateString('es-ES',{month:'long'}):'';return(y==='Todos'||x.date.startsWith(y))&&(m==='Todos'||month===m)&&(s==='Todos'||x.status===s)&&(p==='Todos'||x.priority===p)});$('#filterCount').textContent=`${filtered.length} órdenes visibles`;render()}
loadOrders().then(loaded=>{if(loaded){initFilters();apply()}});
